apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-updater
spec:
#  suspend: true
  schedule: "10 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secret-creator
          containers:
          - name: create-secrets
            image: dtzar/helm-kubectl
            command:
            - /bin/bash
            - -c
            - |
              IFS=$'\n'
              for line in $(cat /etc/target-namespaces/namespaces.txt); do
                namespace=$(echo $line | cut -d ' ' -f1)
                secret_name=$(echo $line | cut -d ' ' -f2)
                kubectl create secret tls $secret_name --cert=/etc/letsencrypt/live/slack.house/fullchain.pem --key=/etc/letsencrypt/live/slack.house/privkey.pem --namespace=$namespace --dry-run=client -o yaml | kubectl apply -f -
              done
            volumeMounts:
            - name: letsencrypt
              mountPath: /etc/letsencrypt
            - name: target-namespaces
              mountPath: /etc/target-namespaces
          restartPolicy: OnFailure
          volumes:
          - name: letsencrypt
            persistentVolumeClaim:
              claimName: letsencrypt
          - name: target-namespaces
            configMap:
              name: target-namespaces
