apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certbot-pvc.yaml
  - certbot-service-account.yaml
  - certbot-rbac-role.yaml
  - certbot-rbac-rolebinding.yaml
  - certbot-cron.yaml
  - certbot-cron-secret-updater.yaml

configMapGenerator:
- name: target-namespaces
  files:
  - ./conf/namespaces.txt
