apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
  namespace: mosquitto
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: harvester
    resources:
        requests:
          storage: 10Gi
