apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt-cluster
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-websockets
      port: 9001
      targetPort: 9001
  type: ClusterIP
